---
# Source: resource/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ksp-resource
  namespace: "moresec-system"
  labels:
    helm.sh/chart: resource-1.0.0
    app.kubernetes.io/name: resource
    app.kubernetes.io/instance: ksp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  web_res: |

    server {
        listen 80;
        server_name localhost;
        root  /home/moresec/storage/;

        location / {
            autoindex on; # 如果需要列出文件，则保留on，否则设置为off
            autoindex_exact_size off;
            autoindex_localtime on;
            charset utf-8;
            auth_basic "Restricted Access"; # 提示用户输入凭据的信息
            auth_basic_user_file /etc/nginx/.htpasswd; # 指向包含用户名和密码的文件
        }
    }
---
# Source: resource/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: ksp-resource
  namespace: "moresec-system"
  labels:
    helm.sh/chart: resource-1.0.0
    app.kubernetes.io/name: resource
    app.kubernetes.io/instance: ksp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: resource
      protocol: TCP
      nodePort: 30081
      name: tcp-resource
  selector:
    app.kubernetes.io/name: resource
    app.kubernetes.io/instance: ksp
---
# Source: resource/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksp-resource
  namespace: "moresec-system"
  labels:
    helm.sh/chart: resource-1.0.0
    app.kubernetes.io/name: resource
    app.kubernetes.io/instance: ksp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: resource
      app.kubernetes.io/instance: ksp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: resource
        app.kubernetes.io/instance: ksp
    spec:
      initContainers:
        - name: htpasswd
          image: "htpasswd:1.0.0.0"
          imagePullPolicy: IfNotPresent
          command:
            [
              "/usr/local/bin/htpasswd",
              "-u",
              "admin",
              "-p",
              "surpass@123",
              "-f",
              "/data/.htpasswd"
            ]
          volumeMounts:
            - mountPath: /data
              name: htpasswd-path
      containers:
        - name: ksp-resource
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: resource
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                [
                  "test",
                  "-d",
                  /home/moresec/storage
                ]
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: web_res
            - name: htpasswd-path
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
            - name: storage
              mountPath: /home/moresec/storage
      volumes:
        - name: config
          configMap:
            name: ksp-resource
        - name: htpasswd-path
          emptyDir: { }
        - name: storage
          hostPath:
            path: /home/moresec/storage

