apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "resource.labels" . | nindent 4 }}
data:
  web_res: |
{{ .Files.Get "config/default.conf" | indent 4 }}
