apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "resource.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "resource.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resource.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: htpasswd
          image: "{{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command:
            [
              "/usr/local/bin/htpasswd",
              "-u",
              "{{ .Values.images.initContainer.args.username }}",
              "-p",
              "{{ .Values.images.initContainer.args.password }}",
              "-f",
              "/data/.htpasswd"
            ]
          volumeMounts:
            - mountPath: /data
              name: htpasswd-path
      containers:
        - name: {{ include "resource.fullname" . }}
          image: "{{ .Values.images.container.repository }}:{{ .Values.images.container.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: resource
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                [
                  "test",
                  "-d",
                  {{ .Values.storage.path }}
              ]
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: web_res
            - name: htpasswd-path
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
            - name: storage
              mountPath: {{ .Values.storage.path }}
      volumes:
        - name: config
          configMap:
            name: {{ include "resource.fullname" . }}
        - name: htpasswd-path
          emptyDir: { }
        - name: storage
          hostPath:
            path: {{ .Values.storage.path }}
