apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "resource.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: resource
      protocol: TCP
      nodePort: 30081
      name: tcp-resource
  selector:
    {{- include "resource.selectorLabels" . | nindent 4 }}
